### PR TITLE
Add ability to hide timer row

### PR DESCRIPTION
**Pull request by eagle6525**
This new feature adds a checkbox to the customization tab to hide/show the row with time information.

Default view is just as before:
prioritab

With the option turned on the row is hidden:
prioritab 2

Annotated image:
prioritab 3

### CODE REVIEW

**Comment by griffedge** [comment]
A quick description of your pull would be helpful!

**Comment by griffedge** [comment]
If prioritab.min.js has been unpacked, shouldn't it just be prioritab.js?

**Comment by eagle6525** [comment]
I agree that if prioritab.min.js has been unpacked it would then be prioritab.js. I was thinking it would be repacked before being merged. It has been repacked now. I just wanted it unpacked for better diffs so you could see the changes I was making.

If I pulled the wrong branch or there is a better way let me know. Also I added a description.

Thanks for your feedback!

**Comment by griffedge** [comment]
Do you think hidden should go under the format options? It's probably going to be used less.

**Comment by eagle6525** [comment]
I put hidden above the format options because if it is checked then the format options are not used at all. In that way hidden is controlling the format options and in my mind should go first.

Either way works for me.

**Comment by eagle6525** [comment]
@griffedge merged your pull request in. Let me know if you want any other changes made. Thanks!

**Pull request merged**
